### PR TITLE
replace all instances of old license text. Fixes #33

### LINKED ISSUE #33: remove references to previous inchi license
As mentioned https://github.com/IUPAC-InChI/InChI/issues/8#issuecomment-1953631931

the [INCHI-1-SRC/LICENCE.pdf](https://github.com/IUPAC-InChI/InChI/blob/main/INCHI-1-SRC/LICENCE.pdf) file should be removed

Additionally, here is a list of places to review and eventually have the license replaced/removed

```
> grep -rl "InChI-Trust Licence" *
INCHI-1-DOC/misc/announce.txt
INCHI-1-DOC/misc/banner-v105-from-alan-2016-02-18.txt
INCHI-1-DOC/misc/banner-v105-final-2016-02-18.txt
INCHI-1-DOC/CHANGELOG.md
INCHI-1-DOC/FAQ/html/inchi-faq.html
INCHI-1-DOC/FAQ/doc/inchi-faq.doc
INCHI-1-DOC/External-contributors/External-contributors
INCHI-1-DOC/readme.txt
INCHI-1-SRC/INCHI_BASE/redundant/aux2atom.h
INCHI-1-SRC/INCHI_BASE/src/sha2.c
INCHI-1-SRC/INCHI_BASE/src/sha2.h
INCHI-1-SRC/INCHI_API/demos/inchi_main/readme.txt
INCHI-1-SRC/INCHI_API/demos/mol2inchi/readme.txt
INCHI-1-SRC/INCHI_API/demos/mol2inchi/src/moreutil.c
INCHI-1-SRC/INCHI_API/demos/mol2inchi/src/mol2inchi.h
INCHI-1-SRC/INCHI_API/demos/mol2inchi/src/moreutil.h
INCHI-1-SRC/INCHI_API/demos/mol2inchi/src/mol2inchi.c
INCHI-1-SRC/INCHI_API/demos/python_sample/readme.txt
INCHI-1-SRC/INCHI_API/demos/readme.txt
INCHI-1-SRC/INCHI_API/demos/test_ixa/readme.txt
INCHI-1-SRC/INCHI_API/demos/test_ixa/src/moreitil.h
INCHI-1-SRC/INCHI_API/demos/test_ixa/src/moreutil.c
INCHI-1-SRC/INCHI_API/demos/test_ixa/src/test_ixa.h
INCHI-1-SRC/INCHI_API/demos/test_ixa/src/test_ixa.c
INCHI-1-SRC/readme.txt
```

Please note, the license of files with no explicit text defaults to the one included in the package so removing all the license info from headers is an option to avoid this kind of issues in the future

### PR DESCRIPTION
**Pull request by giallu**
As agreed in #33 I replaced all the source code instances left of the old license test with the MIT one and removed the PDF file.

As you can see, I actually just removed the license text from readme files, I think it made no sense to also have it there since it is not code.

Few references to the old license can still be found in docs, but it was not clear to me how to fix since there are multiple formats and I am not sure how you build one from the other. See for instance  https://github.com/IUPAC-InChI/InChI/blob/7cb718ffe999945fddfe43acb0cd4920ad302f67/INCHI-1-DOC/FAQ/html/inchi-faq.html#L545-L561 and beyond

My recommendation for the future is to consider removing the license from all files (except those with a different one of course) or at least remove the first lines in all source files so they don't need to be updated. Eg: line 9 should be the first one here:

https://github.com/IUPAC-InChI/InChI/blob/7cb718ffe999945fddfe43acb0cd4920ad302f67/INCHI-1-SRC/INCHI_BASE/src/ichicano.h#L1-L9

### CODE REVIEW

**Comment by djb-rwth** [comment]
Hi @giallu,
Thank you for this pull request.
I assigned @kiddr and @gblanke02 to approve it with whom you have already had an extensive discussion in [Issue #33](https://github.com/IUPAC-InChI/InChI/issues/33).

**Comment by giallu** [comment]
@djb-rwth thanks for the info about the development branch, I will try to remember that.
Please note, you can make this automatic by changing the default branch in the project's settings; if you put `rwth` there all future's PR will be against that branch

**Comment by giallu** [comment]
> I can't comment on the the code amends (which mostly look to be spaces)

Ahhhh sorry, that must be vscode that triggered some reformat on saving. I will push an update that avoids any change not related to licensing

**Comment by djb-rwth** [comment]
> > I can't comment on the the code amends (which mostly look to be spaces)
> 
> Ahhhh sorry, that must be vscode that triggered some reformat on saving. I will push an update that avoids any change not related to licensing

Hi @giallu,
Please do not worry about chaotic whitespaces as they exist all over the code; the corrected ones were also fine (and looked nicer).

**Comment by giallu** [comment]
> Hi @giallu, Please do not worry about chaotic whitespaces as they exist all over the code; the corrected ones were also fine (and looked nicer).

Yeah, it looked nicer but from personal experience it's better to avoid mixing different topics in the same commit/PR

If desired, we can mass reformat the sources with some tool like that in another PR

**Comment by djb-rwth** [comment]
Approved by Gerd Blanke as well. Merging.

**Pull request merged**
